# Generated by Django 3.0.6 on 2020-05-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200522_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='roomName',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
