# Generated by Django 3.0.6 on 2020-05-24 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_roomname'),
    ]

    operations = [
        migrations.CreateModel(
            name='roomName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('password', models.CharField(blank=True, max_length=300, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('time_created', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='roomName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.roomName'),
        ),
    ]
