# Generated by Django 3.0.6 on 2020-05-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20200524_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomname',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
