# Generated by Django 3.0.6 on 2020-06-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20200524_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomname',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='rooms',
            field=models.ManyToManyField(to='chat.roomName'),
        ),
    ]
